export enum ErrorCode {
  // Config errors
  NO_RESPONSE = 'NO_RESPONSE',
  SERVER_STATUS_NOT_OK = 'SERVER_STATUS_NOT_OK',
  INVALID_CONFIG_FORMAT = 'INVALID_CONFIG_FORMAT',
  INVALID_PRESETTINGS_FORMAT = 'INVALID_PRESETTINGS_FORMAT',
  CONFIG_NOT_LOADED = 'CONFIG_NOT_LOADED',

  // Auth errors
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  CRYPTO_NOT_INITIALIZED = 'CRYPTO_NOT_INITIALIZED',

  // Judge errors
  JUDGE_FAILED = 'JUDGE_FAILED',
  UNSUPPORTED_LANGUAGE = 'UNSUPPORTED_LANGUAGE',
  FILE_READ_ERROR = 'FILE_READ_ERROR',

  // Network errors
  NETWORK_ERROR = 'NETWORK_ERROR',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',

  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
